extends RefCounted
class_name FloodFill

## FloodFill — 4-connected reachability check on a tile set.
##
## Used by Catacombs to verify that every room generated by BSPDungeon is
## actually reachable from the entrance. If `validate()` returns false, the
## level should regenerate with a new seed (the BSP corridor builder is
## conservative, but a degenerate split + non-overlapping rooms can theoretically
## leave an island — fail loud rather than ship an unwinnable map).

const NEIGHBOURS: Array[Vector2i] = [
	Vector2i(1, 0),
	Vector2i(-1, 0),
	Vector2i(0, 1),
	Vector2i(0, -1),
]


static func reachable_from(start: Vector2i, walkable: Dictionary) -> Dictionary:
	var seen: Dictionary = {}
	if not walkable.has(start):
		return seen
	var stack: Array[Vector2i] = [start]
	seen[start] = true
	while not stack.is_empty():
		var cur: Vector2i = stack.pop_back()
		for d: Vector2i in NEIGHBOURS:
			var n: Vector2i = cur + d
			if walkable.has(n) and not seen.has(n):
				seen[n] = true
				stack.append(n)
	return seen


static func validate(start: Vector2i, walkable: Dictionary) -> bool:
	var seen: Dictionary = reachable_from(start, walkable)
	return seen.size() == walkable.size()


static func unreachable_count(start: Vector2i, walkable: Dictionary) -> int:
	return walkable.size() - reachable_from(start, walkable).size()
